<?php

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function commerceiats_demo_direct_debit_commerce_checkout_pane_info_alter(&$checkout_panes) {
  // Disable non-Direct Debit checkout panes.
  $checkout_panes['cart_contents']['page'] = 'disabled';
  $checkout_panes['account']['page'] = 'disabled';
  $checkout_panes['customer_profile_billing']['page'] = 'disabled';
  $checkout_panes['checkout_review']['page'] = 'disabled';
  $checkout_panes['commerce_payment']['page'] = 'disabled';
  $checkout_panes['checkout_completion_message']['page'] = 'disabled';

  // Assign Direct Debit checkout panes to the correct pages.
  $checkout_panes['checkout_recurring']['page'] = 'checkout';
  $checkout_panes['checkout_direct_debit_declaration']['page'] = 'declaration';
  $checkout_panes['checkout_direct_debit_account_payer']['page'] = 'account_details';
  $checkout_panes['checkout_direct_debit_validation']['page'] = 'confirmation';
  $checkout_panes['checkout_direct_debit_summary']['page'] = 'review';
  $checkout_panes['checkout_direct_debit_complete']['page'] = 'complete';
}

/**
 * Populates Direct Debit checkout form fields with test data.
 */
function commerceiats_demo_form_commerce_checkout_form_account_details_alter(&$form, &$form_state, $form_id) {
  $form['checkout_direct_debit_account_payer']['account']['account_holder']['#default_value'] = 'Test User';
  $form['checkout_direct_debit_account_payer']['account']['number']['#default_value'] = '12345678';
  $form['checkout_direct_debit_account_payer']['account']['sort_code']['#default_value'] = '000000';

  $form['checkout_direct_debit_account_payer']['payer']['company_name']['#default_value'] = 'Company';
  $form['checkout_direct_debit_account_payer']['payer']['first_name']['#default_value'] = 'Test';
  $form['checkout_direct_debit_account_payer']['payer']['last_name']['#default_value'] = 'User';
  $form['checkout_direct_debit_account_payer']['payer']['address_1']['#default_value'] = '123 Any Street';
  $form['checkout_direct_debit_account_payer']['payer']['town']['#default_value'] = 'Town';
  $form['checkout_direct_debit_account_payer']['payer']['postcode']['#default_value'] = 'AA1 1AA';
  $form['checkout_direct_debit_account_payer']['payer']['email']['#default_value'] = 'user@example.org';
  $form['checkout_direct_debit_account_payer']['payer']['confirm_email']['#default_value'] = 'user@example.org';
}
